service: invoice-application2

custom:
  paymeTransTableName: 'payme-transactions-table-${opt:stage, self:provider.stage}'
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}

  dynamodb:
    start:
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: false
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${self:custom.currentStage}
  region: us-east-1
  environment:
    PAYME_TABLE: ${self:custom.paymeTransTableName}
    IS_OFFLINE: true
    PAYME_URL: ${file(./config.${opt:stage, 'dev'}.json):payme_url}
    PAYME_CALLBACK_URL: ${file(./config.${opt:stage, 'dev'}.json):payme_api_key}
    PAYME_API_KEY: ${file(./config.${opt:stage, 'dev'}.json):payme_api_key}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "PaymeTransactionsDynamoDBTable", "Arn" ] }

functions:
  generateCell:
    handler: index.handler
    events:
      - http:
          path: /generate-cell
          method: post
          cors: true
  pmeListener:
    handler: index.handler
    events:
      - http:
          path: /pme-listener
          method: post
          cors: true
  getPmeStatus:
    handler: index.handler
    events:
      - http:
          path: /get-pme-status
          method: get
          cors: true

resources:
  Resources:
    PaymeTransactionsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: sale_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: sale_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: user_id-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: timestamp-index
            KeySchema:
              - AttributeName: timestamp
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.paymeTransTableName}
