service: invoice-application2

custom:
  tableName: 'invoices-users-table-${self:provider.stage}'
  invoiceTypeTableName: 'invoice-types-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    USERS_TABLE: ${self:custom.tableName}
    TYPE_TABLE: ${self:custom.invoiceTypeTableName}
    IS_OFFLINE: true
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource:
      - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
      - { "Fn::GetAtt": ["InvoiceTypeDynamoDBTable", "Arn" ] }

functions:
  app:
    handler: index.handler
    events:
    - http: ANY /
    - http: 'ANY /{proxy+}'
  getUser:
    handler: index.handler
    events:
    - http: 'GET /invoices/{proxy+}'
  createInvoice:
    handler: index.handler
    events:
    - http: 'POST /invoices'
  createInvoicePdf:
    handler: index.handler
    events:
    - http: 'POST /invoices-pdf'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: ec_number
          AttributeType: S
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: ec_number
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    InvoiceTypeDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
        - AttributeName: type
          AttributeType: N
        - AttributeName: ec_number
          AttributeType: S
        KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: ec_number
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.invoiceTypeTableName}
